# Generated by Django 4.2.5 on 2023-10-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscriptions', '0003_rename_email_subscription_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='isSubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
