# Generated by Django 4.2.5 on 2023-10-10 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_name'),
        ('students', '0002_alter_student_email_alter_student_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='course', to='courses.course'),
        ),
    ]
