# Generated by Django 4.2.5 on 2023-10-06 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0006_alter_course_end_date_alter_course_session_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course', to='courses.course')),
            ],
        ),
    ]
