# Generated by Django 4.2.5 on 2023-10-15 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscriptions', '0002_alter_email_subscription_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Email_subscription',
            new_name='EmailSubscription',
        ),
    ]
