# Generated by Django 4.2.5 on 2023-10-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('sessions', models.IntegerField(blank=True, help_text='Number of sessions')),
                ('session_duration', models.IntegerField(blank=True, help_text='Session duration in minutes')),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('tags', models.TextField(blank=True, max_length=1000)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('image_url', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
