# Generated by Django 4.2.5 on 2023-10-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='test_field',
        ),
    ]
