# Generated by Django 4.2.6 on 2023-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscription',
            name='isSubscribed',
            field=models.BooleanField(default=True),
        ),
    ]
