# Generated by Django 4.2.6 on 2023-10-09 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='session',
            new_name='sessions',
        ),
    ]
