# Generated by Django 4.2.6 on 2023-10-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_session_course_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Name of Course', max_length=50),
        ),
    ]
